version: "3"
services:

  api.dev.docker:
    container_name: "api_container"
    image: api_image
    user: root
    working_dir: /app/www/
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app/
    expose:
      - 3001
    ports:
      - 3001:3001
    env_file:
      - docker/loopback/docker.env
    command: "/./app/docker/loopback/start.sh"
    
  mysql.dev.docker:
    container_name: "mysql_container"
    image: mysql_image
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_aws
    volumes:
      - ./:/app/
    expose:
      - 3306
    ports:
      - 3306:3306